### ISSUE TITLE
Join: User Profile Management

### ISSUE THREAD

**Issue by jpthor** [canyaio/canseek-webui#46]
Current:
No User Management (emails, MM, Name etc)

Desired:
Add minimal User Management:
* Email (and verify)
* MM Address (and add more)
* Name (and edit)
* Company (and edit)

When adding a job post or applying for a job; save all inputted information into the user's profile as "defaults"

ie:

Company
* when first creating a job post, save all job post information into profile as "default"
* when next creating a job post, input all default job post information

User
* when first applying, save all application information into profile as "default"
* when next applying, input all defaults

**Comment by keelymalady** [comment]
Linked to issue #54 

### Description
Add additional verify screen to help users connect metamask account and collect default profile information.
Add confirmation pop up.

### Acceptance Criteria
User clicks 'join' on homescreen',  - the following flow engages
Refer zeplin https://app.zeplin.io/project/5b235559325d7e746d91aaa5/screen/5b693b164e5eeb4df3e1420c

<img width="1077" alt="screen shot 2018-08-07 at 4 29 39 pm" src="https://user-images.githubusercontent.com/39213616/43758335-207c57a0-9a5f-11e8-8f0a-cc6fb53507ee.png">

and, clicks verify the following screen appears
https://app.zeplin.io/project/5b235559325d7e746d91aaa5/screen/5b693b158c7cda51226a959c
<img width="1081" alt="screen shot 2018-08-07 at 4 30 29 pm" src="https://user-images.githubusercontent.com/39213616/43758360-38e791a6-9a5f-11e8-913d-0bbee4bc7e60.png">

**Comment by keelymalady** [comment]
@Xinjie-canya **metamask**
V.1 one metamask address
V1.1 ability to connect multiple metemask addresses =
