### ISSUE TITLE
CANPay Module Integration 

### ISSUE THREAD

**Issue by jpthor** [canyaio/canseek-webui#51]
home -> post a job -> Review

Current
"Pay and Post Job" is poor UX

Desired
Integrate the CANPay module to process the payment. 
Input the amount of CAN into CANPay

**Comment by jpthor** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/41815753/43933171-81b01240-9c8b-11e8-9139-b880f53423cb.png">

This button "Pay and Post Job" should call CANPay module to complete the payment

**Comment by keelymalady** [comment]
@kaiansaari as per discussion CanPay integration TBC by CanWork team
