### ISSUE TITLE
Copy/Wording

### ISSUE THREAD

**Issue by jpthor** [canyaio/canseek-webui#77]
Leave this open until Wording is finalised
@kaiansaari @keelymalady @thetadotonline 

## Job Post Wording
`Recomendation: We recommend an initial reward of 5% of the minimum salary range to attract talent. ` -> 
`Recommendation: We recommend an initial reward of 5% of the minimum salary range to attract talent. `

`Recomendation: We recommend an talent applicaton fee of between $10 - $50 USD`-> `Recommendation: We recommend a talent applicaton fee of between $10 - $50 USD`

`Note: A non refundable 1% fee is paid to the CanYaDAO. ` ->
Note: There is a non-refundable 1% fee. `

### Cancel Post
`Fees: the initial reward will be refunded to the metamask address used to create the job post,less the 1% administration fee.
Any application fees will be refunded to participants.`
->
`Fees: The Initial Reward will be refunded to the metamask address used to create the job post, less the 1% fee.
Any Application Fees will be refunded to participants.`

**Comment by kaiansaari** [comment]
**Post a Job:**
Minor wording, only major issue is _"identity verify"_ but we should streamline. example below.

1- Identity Verify > Your Details / Your Information
2- Job Information > Job Details / Job Information
3- Set Fees and Reward > Fees & Reward
4- Review > Confirm & Pay / Finalise

**Comment by kaiansaari** [comment]
Fee's & Reward screen is busy.
![image](https://user-images.githubusercontent.com/26814804/43933435-fcb39bd2-9c8c-11e8-95db-23f27177925a.png)

**Comment by keelymalady** [comment]
Issue #80 has been created to simplify Fee's and Reward screen

**Comment by keelymalady** [comment]
Issue #82 has been created to simplify "Refer Talent" copy and form placeholder text

**Comment by keelymalady** [comment]
Issue #83 has been created to clarify Post a Job: Metamask address copy

**Comment by Xinjie-canya** [comment]
@keelymalady Could you please pre-fill  data  in the FAQ page?

**Comment by keelymalady** [comment]
### Description
@Xinjie-canya 
New copy change regarding 'applicants' menu
Can we change 'view applicants' to 'review candidates' on the menu below?
<img width="556" alt="screen shot 2018-09-04 at 2 01 54 pm" src="https://user-images.githubusercontent.com/39213616/45009408-5a5ed400-b04b-11e8-8861-71ffcaaac842.png">

### Acceptance Criteria
Review Candidates
<img width="523" alt="screen shot 2018-09-04 at 2 05 06 pm" src="https://user-images.githubusercontent.com/39213616/45009470-aad63180-b04b-11e8-95c5-c22bceaaca3f.png">

**Comment by keelymalady** [comment]
@Xinjie-canya 
### Description
Refer talent - copy update at 'your relationship to the talent'
<img width="894" alt="screen shot 2018-09-04 at 2 42 00 pm" src="https://user-images.githubusercontent.com/39213616/45010414-cabc2400-b050-11e8-9726-22bd3edcf9d2.png">

### Acceptance Criteria
Change 'I'm the talent' to 'I am the talent'
<img width="1061" alt="screen shot 2018-09-04 at 2 42 10 pm" src="https://user-images.githubusercontent.com/39213616/45010429-dd365d80-b050-11e8-87c4-663ae2fb8386.png">

**Comment by Xinjie-canya** [comment]
@keelymalady  done
