### ISSUE TITLE
Pending Status and CanPay notification

### ISSUE THREAD

**Issue by keelymalady** [canyaio/canseek-webui#93]
@Xinjie-canya as discussed - for V1.0 remove pending status from home page

**and
CanPay copy/wording update**

### Description
_Insufficient Balance
You don't have the minimum amount of 45589 CAN required to complete the process. 
Please, buy some CAN and re-check your balance to proceed._

### Acceptance Criteria
_Insufficient Balance to complete transaction
The wallet selected doesn't have the minimum amount of 45589 CAN required to complete the transaction. 
Buy CAN tokens in app via Bancor, MetaMask, or Trezor and re-check your balance to proceed_

**Comment by keelymalady** [comment]
@Xinjie-canya I'm not across all the intergrations of can-pay widget so am hesistant to change. 
Customise the message for canseek only.

**Comment by keelymalady** [comment]
@Xinjie-canya

###Acceptance Criteria
Insufficient Balance to complete transaction
The wallet selected doesn't have the minimum amount of 45589 CAN required to complete the transaction.
Buy CAN tokens below and re-check your balance to proceed

**Comment by Xinjie-canya** [comment]
Same with #95
