### ISSUE TITLE
CanPay copy update

### ISSUE THREAD

**Issue by keelymalady** [canyaio/canseek-webui#95]
### Description
Descriptions on canpay screens 
**screen 1**
_Payment Authorisation
You'll need to authorise the CanSeek Escrow to withdraw 10 CAN from your account.

Please, approve the MetaMask transaction that will popup when you click "Authorise Payment" ._

**screen 2**
Application Fees
_Now, we can proceed with the Application Fees. This final step will allow the CanSeek Escrow to withdraw the authorized 10 CAN to finalize the process.

Please, approve the MetaMask transaction that will popup when you click "Submit"._

<img width="919" alt="screen shot 2018-09-06 at 11 21 53 am" src="https://user-images.githubusercontent.com/39213616/45129972-f9a9d580-b1c9-11e8-894a-578efbdf8a78.png">

### Acceptance Criteria
Update copy as below - no change to formatting or css

**screen 1**
- update copy
_Step 1: Access Authorisation
Authorise the CanSeek Escrow to access your MetaMask wallet. This authorisation is for this transaction only and will enable CanSeek withdraw 10 CAN from your account to pay the application fees in step 2.
Click "Authorise Access" and approve the MetaMask transaction in the popup._

- update button to read "Authorise Access"

**screen 2**
- update copy
_Step 2: Pay Application Fees
This final step will authorise the CanSeek Escrow to withdraw 10 CAN from your MetaMask wallet.
Click "Submit" and approve the MetaMask transaction in the popup._

**Comment by Xinjie-canya** [comment]
@keelymalady i have the same question as #93.
Besides, there are 4 `canya modal instance` generated by `canpay-widget template`, i don't know clearly which do you want to change

**Comment by keelymalady** [comment]
@Xinjie-canya I believe it is the "authorise" stage
after "balance check"
<img width="1331" alt="screen shot 2018-09-13 at 11 02 04 am" src="https://user-images.githubusercontent.com/39213616/45461150-b3fa8900-b744-11e8-98ba-d33a9393174c.png">

**Comment by Xinjie-canya** [comment]
@alsco77 can i change this wording of canpay-lib? see: https://github.com/canyaio/canseek-webui/issues/95#issuecomment-420847942

**Comment by Xinjie-canya** [comment]
I don't think its need to say the same thing via a different way.
